# Generated by Django 5.0 on 2023-12-06 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatgpt', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chathistory',
            name='session_id',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
